CREATE TABLE CLIENTE(
    ID BIGSERIAL,
    NASCIMENTO DATE NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(255),
    CPF VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(14),
    EMAIL VARCHAR(100),
    DATA_CADASTRO DATE,
    PRIMARY KEY(ID)
);