
CREATE TABLE VENDA (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	CLIENTE_ID BIGINT REFERENCES CLIENTE (ID) NOT NULL,
	FORMA_PAGAMENTO VARCHAR(8) CHECK ( FORMA_PAGAMENTO IN ('DINHEIRO', 'CARTAO')) NOT NULL,
	TOTAL NUMERIC(16,2) NOT NULL
);

CREATE TABLE ITEM_VENDA (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	VENDA_ID BIGINT REFERENCES VENDA (ID) NOT NULL,
	PRODUTO_ID BIGINT REFERENCES PRODUTO (ID) NOT NULL,
	QUANTIDADE INTEGER NOT NULL
);
