import type { Metadata } from "next";
import "bulma/css/bulma.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-br">
      <head>
        <title>Vendas app</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
